### ISSUE TITLE
Spike todo list

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/flux#1]
- [x] Single entry for substitution replacements
- [x] Add pre/post context
- [x] Remove glyph from rule
- [x] Combo box for glyph selection
- [x] Drag/drop classes
- [x] Finish drag/drop feature
- [x] Save project file
- [x] New project
- [x] Generate fea
- [x] Generate otf
- [x] Track down random segfaults in `arrangeSlots`
- [x] FontFeatures plugins
- [x] Import fea
- [ ] Import FEE
- [x] Anchor editing

**Comment by simoncozens** [comment]
Nice-to-haves:

- [x] Debugger opens feature/lookup after row selection
- [ ] Debugger shows which rules matched within routine!
- [x] Save plugins output as parameters (input to plugin) not rules (output of plugin)
- [x] Support debugging with a glyph buffer

**Comment by simoncozens** [comment]
Known horrible bugs:

- [x] Glyph class editor not working
- [x] Ligature substitution editing widget not showing
- [x] Pre-/post- context not correctly identified (eg. in RA_to_vLiquid)
- [x] Glyphs components not displaying correctly.
- [ ] Ignore the rule currently being edited while shaping the "before" view
- [x] After view sometimes not working?
- [x] Long glyph names not wrapped/displayed in GlyphBox
- [ ] Predicates "or" / "ends with" etc. not restored in complex computed glyph classes
- [x] Glyph slots in editor need to be in a scroll box
- [ ] glyphHolder.l widgets in editor sometimes not clicking properly.
- [x] Rules containing classes not correctly previewed/debugged.
- [x] Need to zero out bases during shaping preview
- [ ] Rule positioning preview not working correctly
- [x] Routine names not stored correctly when editing chaining rules!
- [x] Routine address information is getting out of hand

**Comment by simoncozens** [comment]
Other nice-to-haves:

- [x] Show computed class on hover
- [x] General regex substitution plugin
- [x] Add to Feature... in Routine list
- [x] Feature friendly names
- [x] Reorder lookups (Must have)
- [x] Lookup subheads

**Comment by simoncozens** [comment]
Font export need-to-haves:

- [ ] Set metadata (version, copyright, etc.)
- [ ] Default checking in babelfont
